
-- DROP USER PAS CASCADE;
CREATE USER PAS IDENTIFIED BY pas 
DEFAULT TABLESPACE "TBS_PAS"
TEMPORARY TABLESPACE "TBS_TMP";

-- ROLES
GRANT "JAVAUSERPRIV" TO PAS WITH ADMIN OPTION;
GRANT "RESOURCE" TO PAS WITH ADMIN OPTION;
GRANT "DBA" TO PAS WITH ADMIN OPTION;
GRANT "JAVASYSPRIV" TO PAS WITH ADMIN OPTION;
GRANT "CONNECT" TO PAS WITH ADMIN OPTION;
ALTER USER PAS DEFAULT ROLE "JAVAUSERPRIV","RESOURCE","DBA","JAVASYSPRIV","CONNECT";

-- SYSTEM PRIVILEGES
GRANT CREATE ANY INDEX TO PAS WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO PAS WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO PAS WITH ADMIN OPTION;
grant create session to PAS;
grant select on SYS.DBA_DATA_FILES to PAS;
grant select on SYS.DBA_FREE_SPACE to PAS;
grant select on SYS.DBA_TABLESPACES to PAS;
grant create sequence to PAS;
grant drop any sequence to PAS;
quit
