set verify off
set echo off

DEFINE username=&1
DEFINE password=&2

CREATE USER &1 IDENTIFIED BY &2 DEFAULT TABLESPACE "TBS_PAS" TEMPORARY TABLESPACE "TBS_TMP";

--在建用户后执行,授权：;

-- ROLES
GRANT "JAVAUSERPRIV" TO &1 WITH ADMIN OPTION;
GRANT "RESOURCE" TO &1 WITH ADMIN OPTION;
GRANT "DBA" TO &1 WITH ADMIN OPTION;
GRANT "JAVASYSPRIV" TO &1 WITH ADMIN OPTION;
GRANT "CONNECT" TO &1 WITH ADMIN OPTION;
ALTER USER &1 DEFAULT ROLE "JAVAUSERPRIV","RESOURCE","DBA","JAVASYSPRIV","CONNECT";

-- SYSTEM PRIVILEGES
GRANT CREATE ANY INDEX TO &1 WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO &1 WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO &1 WITH ADMIN OPTION;
grant create session to &1;
grant select on SYS.DBA_DATA_FILES to &1;
grant select on SYS.DBA_FREE_SPACE to &1;
grant select on SYS.DBA_TABLESPACES to &1;
grant create sequence to &1;
grant drop any sequence to &1;
quit
