DEFINE user_id=&1
DEFINE password=&2

-- DROP USER PAS CASCADE;
CREATE USER $user_id IDENTIFIED BY $password 
DEFAULT TABLESPACE "TBS_PAS"
TEMPORARY TABLESPACE "TBS_TMP";


-- ROLES
GRANT "JAVAUSERPRIV" TO $user_id WITH ADMIN OPTION;
GRANT "RESOURCE" TO $user_id WITH ADMIN OPTION;
GRANT "DBA" TO $user_id WITH ADMIN OPTION;
GRANT "JAVASYSPRIV" TO $user_id WITH ADMIN OPTION;
GRANT "CONNECT" TO $user_id WITH ADMIN OPTION;
ALTER USER $user_id DEFAULT ROLE "JAVAUSERPRIV","RESOURCE","DBA","JAVASYSPRIV","CONNECT";

-- SYSTEM PRIVILEGES
GRANT CREATE ANY INDEX TO $user_id WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO $user_id WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO $user_id WITH ADMIN OPTION;
grant create session to $user_id;
grant select on SYS.DBA_DATA_FILES to $user_id;
grant select on SYS.DBA_FREE_SPACE to $user_id;
grant select on SYS.DBA_TABLESPACES to $user_id;
grant create sequence to $user_id;
grant drop any sequence to $user_id;
quit
