DROP TABLESPACE TBS_MXZ INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TBS_NBZZ INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TBS_JXDX INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TBS_JKSJ INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TBS_LSB INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TBS_PAS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TBS_IDX INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TBS_TMP INCLUDING CONTENTS AND DATAFILES;
